# Generated by Django 2.2.5 on 2019-09-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish',
            options={'verbose_name_plural': 'wishes'},
        ),
    ]
